new
DhanushNehru/Hacktoberfest2024 pull request #270
Opened 2024-10-15 16:00 UTC by codervipul775

2024-10-16 06:07 UTC, hasan-py requested changes
Please give a convenient PR title.

2024-10-16 06:19 UTC, codervipul775 commented
updated.

2024-10-17 16:13 UTC, hasan-py requested changes

2024-10-17 16:13 UTC, hasan-py commented on README.md
> +institution/company: Newton School of Technology
Why you updated the main readme file?

2024-10-18 15:54 UTC, hasan-py approved these changes
LGTM, Thanks!

2024-10-18 15:54 UTC, merged

2024-10-18 15:56 UTC, codervipul775 commented
Why this repository is excluded from hactoberfest

2024-10-18 16:37 UTC, DhanushNehru commented
Hi @codervipul775  this is just a template repo to fork and raise a PR

Checkout repos [here to contribute that counts towards hacktoberfest](https://medium.com/@dhanushnehru/kickstart-hacktoberfest-with-these-exciting-open-source-projects-to-contribute-to-03a61cc43d0d?sk=28f95a04e212f16c5f7c3ba4b3fd5f31)  and join discord for more discussions