Added Backtracking
DhanushNehru/Hacktoberfest2024 pull request #403
Opened 2024-10-27 15:23 UTC by yesiamrajeev

#380

2024-10-27 15:45 UTC, DhanushNehru commented
Hi @yesiamrajeev  please follow this [updated guidelines](https://github.com/DhanushNehru/Hacktoberfest2024/blob/main/PULL_REQUEST_TEMPLATE.md)

2025-06-21 14:50 UTC, SrishtiSinha2003 requested changes

2025-06-21 14:50 UTC, SrishtiSinha2003 commented on Java/Backtracking.java
> +        for (long i : fC) {
Use Arrays.toString() to Print Arrays

2025-06-21 14:50 UTC, SrishtiSinha2003 commented on Java/Backtracking.java
> +        for (long i : fC) {
` System.out.println("Computed Fibonacci cache: " + Arrays.toString(fibCache));`

2025-06-22 17:53 UTC, merged